In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
print('Welcome Ted')

Welcome Ted


In [2]:
Thevenin = pd.read_excel('Donnee Finance.xlsx')

In [3]:
Thevenin.head()

periode  recette fiscale  recette non fiscale  depenses   finacement   \
0   January-05            13571                  288      19518       -10312   
1  February-05            10427                  643      21658         2865   
2     March-05            16270                  494      20191        -3940   
3     April-05            15443                  354      22045         2074   
4       May-05            10818                 1037      23497         2969   

   Budget  
0   23066  
1   35594  
2   33016  
3   39918  
4   38323

In [4]:
impundu =Thevenin.drop('periode', axis=1)

In [5]:
Thevenin.describe().round(2)

recette fiscale  recette non fiscale  depenses   finacement      Budget
count           198.00               198.00     198.00       198.00     198.00
mean          42524.10              4108.07   74375.10     13243.23  134820.20
std           22934.37              3828.80   45172.37     29054.89   86283.53
min           10427.00               288.00     109.00    -78737.00   -9638.00
25%           22251.75              1027.25   40006.75      1655.75   67360.00
50%           39958.50              3241.50   70607.50     10049.00  129248.00
75%           57673.00              5584.50   99653.75     24019.25  184190.75
max          105112.00             20078.00  409881.00    285662.00  798923.00

In [6]:
impundu.head()

recette fiscale  recette non fiscale  depenses   finacement   Budget
0            13571                  288      19518       -10312   23066
1            10427                  643      21658         2865   35594
2            16270                  494      20191        -3940   33016
3            15443                  354      22045         2074   39918
4            10818                 1037      23497         2969   38323

In [7]:
x= impundu.drop('Budget', axis=1)
y = impundu['Budget']

In [8]:
x

recette fiscale  recette non fiscale  depenses   finacement 
0              13571                  288      19518       -10312
1              10427                  643      21658         2865
2              16270                  494      20191        -3940
3              15443                  354      22045         2074
4              10818                 1037      23497         2969
..               ...                  ...        ...          ...
193            72735                 5196     117507        17661
194           101133                 9562     137038        -6707
195            89860                10818     131189        14668
196            79749                 6835     141569        31193
197           105112                16377     229632        78665

[198 rows x 4 columns]

In [9]:
corr_matrix = Thevenin.corr().round(2)
corr_matrix

recette fiscale  recette non fiscale  depenses   \
recette fiscale                 1.00                 0.60       0.79   
recette non fiscale             0.60                 1.00       0.49   
depenses                        0.79                 0.49       1.00   
finacement                      0.24                 0.10       0.67   
Budget                          0.79                 0.50       0.97   

                     finacement   Budget  
recette fiscale             0.24    0.79  
recette non fiscale         0.10    0.50  
depenses                    0.67    0.97  
finacement                  1.00    0.76  
Budget                      0.76    1.00

In [10]:
# Splitting the dataset into training and test set.  
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.2, random_state=0)

In [11]:
#Fitting the MLR model to the training set:  
from sklearn.linear_model import LinearRegression  
regressor= LinearRegression()  
regressor.fit(x_train, y_train)

LinearRegression()

In [12]:
#Predicting the Test set result;  
y_pred= regressor.predict(x_test)
y_pred 

array([ 62189.47420894, 261201.20811757,  77485.67401634, 199071.38067557,
         1740.76571668, 116338.03918824,  46275.85955826, 150439.47909981,
        52110.11265542, 167182.63815902,  61932.74878724, 137884.25785964,
       196941.83058672,  97277.11406463, 126727.76857781,  58929.55683497,
        60611.29215671, 186846.32167484,  66114.15255263, 166864.69775055,
       208243.58996459, 198770.2698198 ,  45383.66039872, 230370.63867317,
       144169.28618837, 148081.92712707, 280405.80084471, 200177.57408882,
       119994.69181179,  56810.76715487,  39819.31383   , 184910.30798605,
       161264.44614962,  83517.05609598,  68127.12093672, 242418.81450249,
       186919.08501872,  38243.45112343,  85342.52853405, 144868.66690802])

In [13]:
print('Train Score: ', regressor.score(x_train, y_train))  
print('Test Score: ', regressor.score(x_test, y_test))

Train Score:  0.9932262977561602
Test Score:  0.9954478450775947


In [14]:
regressor.intercept_.round(2)

1524.94

In [15]:
regressor.coef_.round(2)

array([1.37, 1.15, 0.72, 1.23])

In [16]:
import statsmodels.api as smf 

In [17]:
x = np.append(arr = np.ones((198,1)).astype(int), values=x, axis=1)

In [18]:
x_opt=x [:, [0,1,2,3,4]]  

In [19]:
regressor_OLS=smf.OLS(endog = y, exog=x_opt).fit()  
regressor_OLS.summary()  

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                 Budget   R-squared:                       0.994
Model:                            OLS   Adj. R-squared:                  0.994
Method:                 Least Squares   F-statistic:                     7556.
Date:                Tue, 01 Mar 2022   Prob (F-statistic):          8.32e-211
Time:                        11:54:28   Log-Likelihood:                -2029.8
No. Observations:                 198   AIC:                             4070.
Df Residuals:                     193   BIC:                             4086.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       1437.7186   1073.188      1.340      0.182    -678.965    3554.402
x1             1.3056      0.047     28.024      0.000       1.214       1.398
x2             1.0606      0.164      6.474      0.000       0.737       1.384
x3             0.7793      0.031     25.534      0.000       0.719       0.839
x4             1.1740      0.030     38.808      0.000       1.114       1.234
==============================================================================
Omnibus:                      366.760   Durbin-Watson:                   2.087
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           114436.397
Skew:                           9.764   Prob(JB):                         0.00
Kurtosis:                     119.145   Cond. No.                     2.19e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.19e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [20]:
#from sklearn.metrics import confusion_matrix
#ted_lr = confusion_matrix(y_test, y_pred)
#ted_lr

In [21]:
# from sklearn.neighbors import KNeighborsClassifier
# knn_fin = KNeighborsClassifier(n_neighbors =5,n_jobs = -1,leaf_size = 60,algorithm='brute')

In [22]:
# knn_fin.fit(x_train,y_train)

In [23]:
# y_pred_knn = knn_fin.predict(x_test)
# y_pred_knn


In [24]:
# print('Train Score: ', knn_fin.score(x_train, y_train))  
# print('Test Score: ', knn_fin.score(x_test, y_test))

In [25]:
from sklearn import svm
svm_clf = svm.SVC(kernel ='linear')

In [26]:
svm_clf.fit(x_train,y_train)

SVC(kernel='linear')

In [27]:
y_pred_svm =svm_clf.predict(x_test)

In [28]:
y_pred_svm

array([ 60674, 248898,  71497, 209211,  55640, 111846,  50830, 141675,
        51744, 155671,  81899, 129177, 177259,  83669, 124486,  60674,
        62143, 191210,  60674, 155671, 205608, 209469,  62536, 237455,
       144138, 139593, 289388, 209211, 145998,  57001,  40722, 179774,
       158656,  81899,  57509, 220701, 192680,  35594,  82285, 141868],
      dtype=int64)

In [29]:
from sklearn.metrics import confusion_matrix
ted_svm = confusion_matrix(y_test, y_pred_svm)
ted_svm

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [30]:
from sklearn.metrics import accuracy_score
svm_result = accuracy_score(y_test,y_pred_svm)
print("Accuracy :",svm_result)

Accuracy : 0.0


In [44]:
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test= train_test_split(impundu.drop(['Budget'], axis='columns'),impundu.Budget, test_size= 0.2, random_state=0)

In [53]:

from sklearn.ensemble import RandomForestRegressor

In [68]:
clf = RandomForestRegressor(n_estimators=50, max_depth=2, random_state=0)
clf.fit(x_train, y_train)

RandomForestRegressor(max_depth=2, n_estimators=50, random_state=0)

In [69]:
y_pred= clf.predict(x_test)

In [70]:
y_pred

array([ 61775.9839344 , 221089.27676727,  61775.9839344 , 196461.84944169,
       103735.31110508, 103735.31110508,  61038.8358094 , 142288.90348453,
        61038.8358094 , 179163.79569015, 102375.45716436, 105245.42391214,
       192110.35194   ,  91022.73387441, 135512.5644151 ,  61775.9839344 ,
        61775.9839344 , 186978.09219619,  61775.9839344 , 179163.79569015,
       199315.0397354 , 196461.84944169,  70308.29776769, 218371.80447143,
       135512.5644151 , 156369.89335201, 228624.84965616, 196461.84944169,
       165684.27280705,  68906.07879595,  61038.8358094 , 179163.79569015,
       179163.79569015, 134152.71047439,  61775.9839344 , 254889.9300185 ,
       188292.71015688,  61038.8358094 ,  94481.27953156, 142288.90348453])

In [71]:
clf.score(x_test,y_test)

0.8937347265598382